version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: cv_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: cv_frontend
    ports:
      - "80:80"
    depends_on:
      - backend